import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "@/components/sideMenu.client";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen flex">
      <SideMenu />
      <div className="h-full w-full container mx-auto p-6">{children}</div>
    </div>
  );
}
