/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1RH2NIFGtz0
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="min-h-screen flex items-center justify-center px-4">
      <div className="max-w-md w-full space-y-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Sign in to your account</h1>
          <p className="text-sm font-medium leading-none text-gray-500">Enter your details below</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input id="username" placeholder="john.doe" required />
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label className="mb-0" htmlFor="password">
                Password
              </Label>
              <Link className="ml-2 text-sm font-medium text-blue-600 hover:text-blue-700" href="#">
                Forgot password?
              </Link>
            </div>
            <Input id="password" placeholder="Enter your password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Sign in
          </Button>
        </div>
      </div>
    </div>
  )
}
